### test movies lists:
### discover popular movies, page 1 (10000) results
GET https://api.themoviedb.org/3/discover/movie?api_key=eb066629e9e5aca99797f3955400c4bd&language=en-US&sort_by=popularity.desc&include_adult=true&include_video=false&page=1
### Movie Details
GET https://api.themoviedb.org/3/movie/464052?api_key=eb066629e9e5aca99797f3955400c4bd
### Movie Genres
GET https://api.themoviedb.org/3/genre/movie/list?api_key=eb066629e9e5aca99797f3955400c4bd
